app = "65dza165d16za6"
primary_region = "cdg"

[processes]
app = "npm start"  # Your bot startup command

[vm]
cpu_kind = "shared"
cpus = 1
memory = "2gb"

# REMOVE [mounts] unless you actually need a volume
# REMOVE [http_service] completely
