app = "65dza165d16za6"
primary_region = "cdg"

[vm]
cpu_kind = "shared"
cpus = 2
memory = "2gb"

[processes]
app = "npm start"

# This ensures only 1 machine
[deploy]
max_per_region = 1
release_command = ""
