app = "65dza165d16za6"
primary_region = "cdg"

# VM configuration
[vm]
cpu_kind = "shared"
cpus = 1
memory = "2gb"

# Your bot process
[processes]
app = "npm start"

# OPTIONAL: If you want to ensure it never scales to zero
[compute]
memory = "2GB"
